item_table = {
    "Bow": (0, 0),
    "Progressive Bow": (0, 1),
    "Silver Arrows": (0, 3),
    "Blue Boomerang": (0, 4),
    "Red Boomerang": (0, 5),
    "Hookshot": (0, 6),
    "Mushroom": (0, 7),
    "Magic Powder": (0, 8),
    "Fire Rod": (1, 0),
    "Ice Rod": (1, 1),
    "Bombos": (1, 2),
    "Ether": (1, 3),
    "Quake": (1, 4),
    "Lamp": (1, 5),
    "Hammer": (1, 6),
    "Shovel": (1, 7),
    "Ocarina": (1, 8),
    "Bug Catching Net": (2, 0),
    "Book of Mudora": (2, 1),
    "Cane of Somaria": (2, 2),
    "Cane of Byrna": (2, 3),
    "Cape": (2, 4),
    "Magic Mirror": (2, 5),
    "Single Bomb": (2, 6),
    "Bombs (3)": (2, 7),
    "Bombs (10)": (2, 8),
    "Bottle": (3, 0),
    "Bottle (Red Potion)": (3, 1),
    "Bottle (Green Potion)": (3, 2),
    "Bottle (Blue Potion)": (3, 3),
    "Bottle (Bee)": (3, 4),
    "Bottle (Good Bee)": (3, 5),
    "Bottle (Fairy)": (3, 6),
    "Progressive Armor": (4, 0),
    "Blue Mail": (4, 1),
    "Red Mail": (4, 2),
    "Pegasus Boots": (4, 3),
    "Power Glove": (4, 4),
    "Titans Mitts": (4, 5),
    "Progressive Glove": (4, 6),
    "Flippers": (4, 7),
    "Moon Pearl": (4, 8),
    "Piece of Heart": (5, 0),
    "Boss Heart Container": (5, 1),
    "Small Heart": (5, 2),
    "Small Magic": (5, 3),
    "Big Magic": (5, 4),
    "Sanctuary Heart Container": (5, 5),
    "Magic Upgrade (1/2)": (5, 6),
    "Rupee (1)": (6, 0),
    "Rupees (5)": (6, 1),
    "Rupees (20)": (6, 2),
    "Rupees (50)": (6, 3),
    "Rupees (100)": (6, 4),
    "Rupees (300)": (6, 5),
    "Single Arrow": (6, 6),
    "Arrows (5)": (6, 7),
    "Arrows (10)": (6, 8),
    "Fighter Sword": (7, 0),
    "Master Sword": (7, 1),
    "Tempered Sword": (7, 2),
    "Golden Sword": (7, 3),
    "Blue Shield": (7, 4),
    "Red Shield": (7, 5),
    "Mirror Shield": (7, 6),
    "Progressive Sword": (7, 7),
    "Progressive Shield": (7, 8),
}
